import type { Metadata } from "next";
import { Roboto_Mono } from 'next/font/google'
import "./globals.css";
import Navbar from "@/components/navbar";
import { CardProvider } from "@/components/cardContext";
import Footer from "@/components/footer";
import { Toaster } from 'react-hot-toast'

const roboto = Roboto_Mono({
  subsets: ['latin'],
  weight: ["400", "600"],
  preload: true,
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Shopaura",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className} style={{ fontWeight: '600', paddingTop: "60px" }}
      >
        <CardProvider>
          <Navbar />
          {children}
          <Footer />

          <Toaster
            position="top-center"
            reverseOrder={true}
            toastOptions={{
              style: {
                borderRadius: "8px",
                padding: "16px",
                fontSize: "14px",
                minWidth: "200px"
              },
              success: {
                style: {
                  background: "#22C55E",
                  color: "#FFFFFF",
                },
                icon: "✅",
                duration: 2000,
              },
              error: {
                style: {
                  background: "#EF4444",
                  color: "#FFFFFF",
                },
                icon: "❌",
                duration: 2000,
              },
            }}
          />
        </CardProvider>
      </body>
    </html>
  );
}
